import express from "express";
import { StatusCodes } from "http-status-codes";
import { UserService } from "./user_service.js";
import type { User } from "./user_repository.js";

import { isAuthenticated, isAdmin } from "../middleware/auth_handlers.js";

export const userRouter = express.Router();
const userService: UserService = UserService.Instance;

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users/count:
 *   get:
 *     summary: Retrieve the total number of users
 *     security: []
 *     responses:
 *       200:
 *         description: The total number of users.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 count:
 *                   type: integer
 */
userRouter.get("/count", (req, res) => {
  try {
    const count = userService.getUserCount();
    res.status(StatusCodes.OK).json({ count });
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users:
 *   get:
 *     summary: Retrieve a list of users
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: A list of users.
 *       403:
 *         description: Forbidden - Admin role required
 *       401:
 *         description: Unauthorized
 */
userRouter.get("/", isAuthenticated, isAdmin, (req, res) => {
  try {
    const users: User[] = userService.getAllUsers();
    res.status(StatusCodes.OK).json(users);
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users/{id}:
 *   delete:
 *     summary: Delete a user
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The user ID
 *     responses:
 *       200:
 *         description: User deleted successfully
 *       403:
 *         description: Forbidden - Admin role required
 *       404:
 *         description: User not found
 */
userRouter.delete("/:id", isAuthenticated, isAdmin, (req, res) => {
  try {
    const userId = parseInt(req.params.id);
    if (isNaN(userId)) {
      res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid user ID" } });
      return;
    }

    const deleted = userService.deleteUser(userId);
    if (deleted) {
      res.status(StatusCodes.OK).json({ message: "User deleted successfully" });
    } else {
      res.status(StatusCodes.NOT_FOUND).json({ error: { message: "User not found" } });
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});
