import express from "express";
import { StatusCodes } from "http-status-codes";
import { UserService } from "./user_service.js";
import type { User } from "./user_repository.js";

import { isAuthenticated, isAdmin } from "../middleware/auth_handlers.js";
import type { AuthRequest } from "../middleware/auth_handlers.js";
import { UserRole } from "../models/types.js";
import multer from "multer";
import path from "path";

export const userRouter = express.Router();
const userService: UserService = UserService.Instance;

// Configure multer for avatar uploads
const storage = multer.diskStorage({
  destination: (req, file, cb) => {
    cb(null, "avatars/");
  },
  filename: (req, file, cb) => {
    // Generate unique filename with timestamp
    const uniqueSuffix = Date.now() + "-" + Math.round(Math.random() * 1e9);
    cb(null, "avatar-" + uniqueSuffix + path.extname(file.originalname));
  },
});

const fileFilter = (req: any, file: any, cb: any) => {
  // Accept only image files
  const allowedMimes = ["image/jpeg", "image/png", "image/gif", "image/webp"];
  if (allowedMimes.includes(file.mimetype)) {
    cb(null, true);
  } else {
    cb(new Error("Only image files (JPEG, PNG, GIF, WebP) are allowed"), false);
  }
};

const upload = multer({
  storage,
  fileFilter,
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB limit
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users/count:
 *   get:
 *     summary: Retrieve the total number of users
 *     security: []
 *     responses:
 *       200:
 *         description: The total number of users.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 count:
 *                   type: integer
 */
userRouter.get("/count", (req, res) => {
  try {
    const count = userService.getUserCount();
    res.status(StatusCodes.OK).json({ count });
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users:
 *   get:
 *     summary: Retrieve a list of users
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: A list of users.
 *       403:
 *         description: Forbidden - Admin role required
 *       401:
 *         description: Unauthorized
 */
userRouter.get("/", isAuthenticated, isAdmin, (req, res) => {
  try {
    const users: User[] = userService.getAllUsers();
    res.status(StatusCodes.OK).json(users);
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users/{id}:
 *   delete:
 *     summary: Delete a user
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The user ID
 *     responses:
 *       200:
 *         description: User deleted successfully
 *       403:
 *         description: Forbidden - Admin role required
 *       404:
 *         description: User not found
 */
userRouter.delete("/:id", isAuthenticated, isAdmin, (req, res) => {
  try {
    const userId = parseInt(req.params.id);
    const result = userService.deleteUser(userId);
    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json(result.data);
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users/{id}:
 *   put:
 *     summary: Update a user's account details
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The user ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userName:
 *                 type: string
 *               email:
 *                 type: string
 *     responses:
 *       200:
 *         description: User updated successfully
 *       400:
 *         description: Invalid input
  *       403:
  *         description: Forbidden - Not authorized to update this account
  *       404:
  *         description: User not found
  */
userRouter.put("/:id", isAuthenticated, (req, res) => {
  try {
    const userId = parseInt(req.params.id);
    const { userName, email } = req.body;
    const authReq = req as AuthRequest;

    const result = userService.updateUser(
      userId,
      userName,
      email,
      authReq.payload?.user.UserId || 0,
      authReq.payload?.user.Role as UserRole
    );

    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json(result.data);
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

/**
 * @swagger
 * /api/users/{id}/avatar:
 *   post:
 *     summary: Upload a user avatar image
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The user ID
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             properties:
 *               avatar:
 *                 type: string
 *                 format: binary
 *                 description: The avatar image file (JPEG, PNG, GIF, or WebP, max 5MB)
 *     responses:
 *       200:
 *         description: Avatar uploaded successfully
 *       400:
 *         description: Invalid input or unsupported file type
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden - Not authorized to upload avatar for this user
 *       404:
 *         description: User not found
 *       413:
 *         description: File too large
 */
userRouter.post("/:id/avatar", isAuthenticated, (req, res, next) => {
  upload.single("avatar")(req, res, (err: any) => {
    if (err) {
      // Handle multer errors
      if (err.code === "LIMIT_FILE_SIZE") {
        res
          .status(StatusCodes.BAD_REQUEST)
          .json({ error: { message: "File too large. Maximum size is 5MB" } });
      } else if (err.message && err.message.includes("Only image files")) {
        res
          .status(StatusCodes.BAD_REQUEST)
          .json({ error: { message: err.message } });
      } else {
        res
          .status(StatusCodes.BAD_REQUEST)
          .json({ error: { message: err.message || "File upload failed" } });
      }
      return;
    }
    next();
  });
}, (req, res) => {
  try {
    const userId = parseInt(req.params.id);
    const authReq = req as AuthRequest;

    if (!req.file) {
      res
        .status(StatusCodes.BAD_REQUEST)
        .json({ error: { message: "No file uploaded" } });
      return;
    }

    const avatarPath = req.file.path;

    const result = userService.updateUserAvatar(
      userId,
      avatarPath,
      authReq.payload?.user.UserId || 0,
      authReq.payload?.user.Role as UserRole
    );

    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json({ data: result.data });
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/users/{id}/password:
 *   patch:
 *     summary: Change a user's password
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *         description: The user ID
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               currentPassword:
 *                 type: string
 *               newPassword:
 *                 type: string
 *     responses:
 *       200:
 *         description: Password updated successfully
 *       400:
 *         description: Invalid input or missing passwords
 *       401:
 *         description: Incorrect current password
 *       403:
 *         description: Forbidden - Not authorized
 *       404:
 *         description: User not found
 */
userRouter.patch("/:id/password", isAuthenticated, (req, res) => {
  try {
    const userId = parseInt(req.params.id);
    const { currentPassword, newPassword } = req.body;
    const authReq = req as AuthRequest;

    const result = userService.changePassword(
      userId,
      newPassword,
      currentPassword,
      authReq.payload?.user.UserId,
      authReq.payload?.user.Role
    );

    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json(result.data);
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});
