// These tests were generated by Gemini
import request from "supertest";
import { app } from "../app.js";
import { StatusCodes } from "http-status-codes";
import { UserRole } from "../models/types.js";
import jwt from "jsonwebtoken";
import { SECRET_KEY } from "../middleware/auth_handlers.js";
import { Unit } from "../unit.js";
import bcrypt from "bcrypt";

describe("User API", () => {
  it("GET /api/users/count should return the total number of users", async () => {
    const res = await request(app).get("/api/users/count");
    expect(res.status).toBe(StatusCodes.OK);
    expect(res.body).toHaveProperty("count");
    expect(typeof res.body.count).toBe("number");
  });
});

// These tests were generated by Gemini
describe("User Password Change API", () => {
  let adminToken: string;
  let userToken: string;
  let otherUserToken: string;
  let testUserId: number;
  let otherUserId: number;

  beforeAll(() => {
    const adminPayload = { user: { UserId: 9999, Email: "admin@admin.com", Role: UserRole.ADMIN } };
    adminToken = jwt.sign(adminPayload, SECRET_KEY);

    const unit = new Unit(false);
    try {
      const passwordHash = bcrypt.hashSync("oldpassword", 10);
      const res1 = unit.prepare("INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES (?, ?, ?, ?) RETURNING UserId")
        .get("testuser1", `user1-${Date.now()}@test.com`, passwordHash, UserRole.USER) as { UserId: number };
      testUserId = res1.UserId;

      const res2 = unit.prepare("INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES (?, ?, ?, ?) RETURNING UserId")
        .get("testuser2", `user2-${Date.now()}@test.com`, passwordHash, UserRole.USER) as { UserId: number };
      otherUserId = res2.UserId;
      unit.complete(true);
    } catch (e) {
      unit.complete(false);
      throw e;
    }

    userToken = jwt.sign({ user: { UserId: testUserId, Email: "user1@test.com", Role: UserRole.USER } }, SECRET_KEY);
    otherUserToken = jwt.sign({ user: { UserId: otherUserId, Email: "user2@test.com", Role: UserRole.USER } }, SECRET_KEY);
  });

  afterAll(() => {
    const unit = new Unit(false);
    try {
      unit.prepare("DELETE FROM User WHERE UserId IN (?, ?)").run(testUserId, otherUserId);
      unit.complete(true);
    } catch (e) {
      unit.complete(false);
    }
  });

  it("should allow a user to change their own password with the correct current password", async () => {
    const res = await request(app)
      .patch(`/api/users/${testUserId}/password`)
      .set("Authorization", `Bearer ${userToken}`)
      .send({ currentPassword: "oldpassword", newPassword: "newpassword" });
    expect(res.status).toBe(StatusCodes.OK);
  });

  it("should deny a user to change their own password with incorrect current password", async () => {
    const res = await request(app)
      .patch(`/api/users/${otherUserId}/password`)
      .set("Authorization", `Bearer ${otherUserToken}`)
      .send({ currentPassword: "wrongpassword", newPassword: "newpassword" });
    expect(res.status).toBe(StatusCodes.UNAUTHORIZED);
  });

  it("should deny a user to change another user's password", async () => {
    const res = await request(app)
      .patch(`/api/users/${otherUserId}/password`)
      .set("Authorization", `Bearer ${userToken}`)
      .send({ currentPassword: "oldpassword", newPassword: "newpassword" });
    expect(res.status).toBe(StatusCodes.FORBIDDEN);
  });

  it("should allow an admin to change any user's password without current password", async () => {
    const res = await request(app)
      .patch(`/api/users/${otherUserId}/password`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ newPassword: "adminchangedpassword" });
    expect(res.status).toBe(StatusCodes.OK);
  });
});
