// These tests were generated by Gemini
import request from "supertest";
import { app } from "../app.js";
import { StatusCodes } from "http-status-codes";
import { UserRole } from "../models/types.js";
import jwt from "jsonwebtoken";
import { SECRET_KEY } from "../middleware/auth_handlers.js";
import { Unit } from "../unit.js";

describe("User API Extension", () => {
  let adminToken: string;
  let userToken: string;
  let testUserId: number;

  beforeAll(async () => {
    const adminPayload = { user: { UserId: 1, Email: "admin@admin.com", Role: UserRole.ADMIN } };
    adminToken = jwt.sign(adminPayload, SECRET_KEY);

    // Create a temporary test user with unique email
    const uniqueEmail = `test-${Date.now()}@test.com`;
    const unit = new Unit(false);
    try {
      const res = unit.prepare("INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES (?, ?, ?, ?) RETURNING UserId")
        .get("testuser", uniqueEmail, "hash", UserRole.USER) as { UserId: number };
      testUserId = res.UserId;
      unit.complete(true);
    } catch (e) {
      unit.complete(false);
      throw e;
    }

    const userPayload = { user: { UserId: testUserId, Email: uniqueEmail, Role: UserRole.USER } };
    userToken = jwt.sign(userPayload, SECRET_KEY);
  });

  afterAll(async () => {
    if (testUserId) {
      const unit = new Unit(false);
      try {
        unit.prepare("DELETE FROM User WHERE UserId = ?").run(testUserId);
        unit.complete(true);
      } catch (e) {
        unit.complete(false);
      }
    }
  });

  describe("GET /api/users", () => {
    it("should allow admin to get all users", async () => {
      const res = await request(app)
        .get("/api/users")
        .set("Authorization", `Bearer ${adminToken}`);
      expect(res.status).toBe(StatusCodes.OK);
      expect(Array.isArray(res.body)).toBe(true);
    });

    it("should forbid non-admin from getting all users", async () => {
      const res = await request(app)
        .get("/api/users")
        .set("Authorization", `Bearer ${userToken}`);
      expect(res.status).toBe(StatusCodes.FORBIDDEN);
    });
  });

  describe("PUT /api/users/:id", () => {
    it("should allow owner to update their account", async () => {
      const res = await request(app)
        .put(`/api/users/${testUserId}`)
        .set("Authorization", `Bearer ${userToken}`)
        .send({ userName: "updated", email: "updated@test.com" });
      expect(res.status).toBe(StatusCodes.OK);
    });

    it("should allow admin to update any account", async () => {
      const res = await request(app)
        .put(`/api/users/${testUserId}`)
        .set("Authorization", `Bearer ${adminToken}`)
        .send({ userName: "admin-updated", email: "admin-updated@test.com" });
      expect(res.status).toBe(StatusCodes.OK);
    });

    it("should forbid non-owner non-admin from updating account", async () => {
      const res = await request(app)
        .put("/api/users/1") // Admin user ID
        .set("Authorization", `Bearer ${userToken}`)
        .send({ userName: "hacked", email: "hacked@admin.com" });
      expect(res.status).toBe(StatusCodes.FORBIDDEN);
    });

    it("should return 400 for missing fields", async () => {
      const res = await request(app)
        .put(`/api/users/${testUserId}`)
        .set("Authorization", `Bearer ${userToken}`)
        .send({ userName: "only-name" });
      expect(res.status).toBe(StatusCodes.BAD_REQUEST);
    });
  });

  describe("DELETE /api/users/:id", () => {
    it("should forbid non-admin from deleting user", async () => {
      const res = await request(app)
        .delete(`/api/users/${testUserId}`)
        .set("Authorization", `Bearer ${userToken}`);
      expect(res.status).toBe(StatusCodes.FORBIDDEN);
    });

    it("should allow admin to delete user", async () => {
      // Create another temporary user to delete
      let toDeleteId: number;
      const unit = new Unit(false);
      try {
        const row = unit.prepare("INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES (?, ?, ?, ?) RETURNING UserId")
          .get("delete-me", "delete@test.com", "hash", UserRole.USER) as { UserId: number };
        toDeleteId = row.UserId;
        unit.complete(true);
      } catch (e) {
        unit.complete(false);
        throw e;
      }

      const res = await request(app)
        .delete(`/api/users/${toDeleteId}`)
        .set("Authorization", `Bearer ${adminToken}`);
      expect(res.status).toBe(StatusCodes.OK);
    });
  });

  describe("GET /api/users/:id/enrollments", () => {
    it("should allow owner to get their enrollments", async () => {
      const res = await request(app)
        .get(`/api/users/${testUserId}/enrollments`)
        .set("Authorization", `Bearer ${userToken}`);
      expect(res.status).toBe(StatusCodes.OK);
      expect(Array.isArray(res.body)).toBe(true);
    });

    it("should allow admin to get any user's enrollments", async () => {
      const res = await request(app)
        .get(`/api/users/${testUserId}/enrollments`)
        .set("Authorization", `Bearer ${adminToken}`);
      expect(res.status).toBe(StatusCodes.OK);
      expect(Array.isArray(res.body)).toBe(true);
    });

    it("should forbid non-owner non-admin from getting enrollments", async () => {
      const res = await request(app)
        .get("/api/users/1/enrollments") // Admin user ID
        .set("Authorization", `Bearer ${userToken}`);
      expect(res.status).toBe(StatusCodes.FORBIDDEN);
    });
  });
});
