// These tests were generated by Gemini
import request from "supertest";
import { app } from "../app.js";
import { StatusCodes } from "http-status-codes";
import { UserRole } from "../models/types.js";
import jwt from "jsonwebtoken";
import { SECRET_KEY } from "../middleware/auth_handlers.js";
import { Unit } from "../unit.js";
import fs from "fs";
import path from "path";

describe("Avatar Upload Endpoint", () => {
  let adminToken: string;
  let userToken: string;
  let otherUserToken: string;
  let testUserId: number;
  let otherUserId: number;
  const testImagePath = path.join(process.cwd(), "test-avatar.jpg");

  beforeAll(async () => {
    // Create a test image file (minimal JPEG header)
    const jpegBuffer = Buffer.from([
      0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01,
      0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xff, 0xdb, 0x00, 0x43,
      0x00, 0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07, 0x07, 0x07, 0x09,
      0x09, 0x08, 0x0a, 0x0c, 0x14, 0x0d, 0x0c, 0x0b, 0x0b, 0x0c, 0x19, 0x12,
      0x13, 0x0f, 0x14, 0x1d, 0x1a, 0x1f, 0x1e, 0x1d, 0x1a, 0x1c, 0x1c, 0x20,
      0x24, 0x2e, 0x27, 0x20, 0x22, 0x2c, 0x23, 0x1c, 0x1c, 0x28, 0x37, 0x29,
      0x2c, 0x30, 0x31, 0x34, 0x34, 0x34, 0x1f, 0x27, 0x39, 0x3d, 0x38, 0x32,
      0x3c, 0x2e, 0x33, 0x34, 0x32, 0xff, 0xc0, 0x00, 0x0b, 0x08, 0x00, 0x01,
      0x00, 0x01, 0x01, 0x01, 0x11, 0x00, 0xff, 0xc4, 0x00, 0x1f, 0x00, 0x00,
      0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00,
      0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
      0x09, 0x0a, 0x0b, 0xff, 0xc4, 0x00, 0xb5, 0x10, 0x00, 0x02, 0x01, 0x03,
      0x03, 0x02, 0x04, 0x03, 0x05, 0x05, 0x04, 0x04, 0x00, 0x00, 0x01, 0x7d,
      0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21, 0x31, 0x41, 0x06,
      0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xa1, 0x08,
      0x23, 0x42, 0xb1, 0xc1, 0x15, 0x52, 0xd1, 0xf0, 0x24, 0x33, 0x62, 0x72,
      0x82, 0x09, 0x0a, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x25, 0x26, 0x27, 0x28,
      0x29, 0x2a, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x43, 0x44, 0x45,
      0x46, 0x47, 0x48, 0x49, 0x4a, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59,
      0x5a, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6a, 0x73, 0x74, 0x75,
      0x76, 0x77, 0x78, 0x79, 0x7a, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89,
      0x8a, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0xa2, 0xa3,
      0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6,
      0xb7, 0xb8, 0xb9, 0xba, 0xc2, 0xc3, 0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9,
      0xca, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xe1, 0xe2,
      0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xf1, 0xf2, 0xf3, 0xf4,
      0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xff, 0xda, 0x00, 0x08, 0x01, 0x01,
      0x00, 0x00, 0x3f, 0x00, 0xfb, 0xd0, 0xff, 0xd9,
    ]);
    fs.writeFileSync(testImagePath, jpegBuffer);

    // Create admin token
    const adminPayload = { user: { UserId: 1, Email: "admin@admin.com", Role: UserRole.ADMIN } };
    adminToken = jwt.sign(adminPayload, SECRET_KEY);

    // Create a test user
    const uniqueEmail = `avatar-test-${Date.now()}@test.com`;
    const unit = new Unit(false);
    try {
      const res = unit.prepare("INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES (?, ?, ?, ?) RETURNING UserId")
        .get("avatar-testuser", uniqueEmail, "hash", UserRole.USER) as { UserId: number };
      testUserId = res.UserId;
      unit.complete(true);
    } catch (e) {
      unit.complete(false);
      throw e;
    }

    const userPayload = { user: { UserId: testUserId, Email: uniqueEmail, Role: UserRole.USER } };
    userToken = jwt.sign(userPayload, SECRET_KEY);

    // Create another test user for authorization tests
    const otherEmail = `avatar-other-${Date.now()}@test.com`;
    const unit2 = new Unit(false);
    try {
      const res = unit2.prepare("INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES (?, ?, ?, ?) RETURNING UserId")
        .get("avatar-other", otherEmail, "hash", UserRole.USER) as { UserId: number };
      otherUserId = res.UserId;
      unit2.complete(true);
    } catch (e) {
      unit2.complete(false);
      throw e;
    }

    const otherPayload = { user: { UserId: otherUserId, Email: otherEmail, Role: UserRole.USER } };
    otherUserToken = jwt.sign(otherPayload, SECRET_KEY);
  });

  afterAll(async () => {
    // Clean up test users
    if (testUserId) {
      const unit = new Unit(false);
      try {
        unit.prepare("DELETE FROM User WHERE UserId = ?").run(testUserId);
        unit.complete(true);
      } catch (e) {
        unit.complete(false);
      }
    }

    if (otherUserId) {
      const unit = new Unit(false);
      try {
        unit.prepare("DELETE FROM User WHERE UserId = ?").run(otherUserId);
        unit.complete(true);
      } catch (e) {
        unit.complete(false);
      }
    }

    // Clean up test image file
    if (fs.existsSync(testImagePath)) {
      fs.unlinkSync(testImagePath);
    }
  });

  describe("POST /api/users/:id/avatar - Successful uploads", () => {
    it("should allow user to upload their own avatar", async () => {
      const res = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.OK);
      expect(res.body).toHaveProperty("data.message", "Avatar uploaded successfully");
      expect(res.body).toHaveProperty("data.avatarPath");
      expect(res.body.data.avatarPath).toMatch(/^avatars\/avatar-/);
    });

    it("should allow admin to upload avatar for any user", async () => {
      const res = await request(app)
        .post(`/api/users/${otherUserId}/avatar`)
        .set("Authorization", `Bearer ${adminToken}`)
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.OK);
      expect(res.body).toHaveProperty("data.message", "Avatar uploaded successfully");
      expect(res.body).toHaveProperty("data.avatarPath");
    });

    it("should update avatar path in database", async () => {
      await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      // Verify avatar path was stored in database
      const unit = Unit.createReadonly();
      try {
        const user = unit.prepare("SELECT AvatarPath FROM User WHERE UserId = ?")
          .get(testUserId) as { AvatarPath: string | null };
        expect(user).toBeDefined();
        expect(user.AvatarPath).toBeTruthy();
        expect(user.AvatarPath).toMatch(/^avatars\/avatar-/);
      } finally {
        unit.complete();
      }
    });

    it("should generate unique filenames for multiple uploads", async () => {
      const res1 = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      // Small delay to ensure different timestamp
      await new Promise(resolve => setTimeout(resolve, 100));

      const res2 = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      const path1 = res1.body.data.avatarPath;
      const path2 = res2.body.data.avatarPath;

      expect(path1).not.toEqual(path2);
      expect(path1).toMatch(/avatars\/avatar-/);
      expect(path2).toMatch(/avatars\/avatar-/);
    });
  });

  describe("POST /api/users/:id/avatar - Authorization", () => {
    it("should forbid user from uploading avatar for another user", async () => {
      const res = await request(app)
        .post(`/api/users/${otherUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.FORBIDDEN);
      expect(res.body).toHaveProperty("error");
      expect(res.body.error.message).toContain("not authorized");
    });

    it("should return 401 when no token provided", async () => {
      const res = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.UNAUTHORIZED);
    });

    it("should return 401 with invalid token", async () => {
      const res = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", "Bearer invalid-token")
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.UNAUTHORIZED);
    });
  });

  describe("POST /api/users/:id/avatar - File validation", () => {
    it("should reject requests with no file", async () => {
      const res = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`);

      expect(res.status).toBe(StatusCodes.BAD_REQUEST);
      expect(res.body.error.message).toContain("No file uploaded");
    });

    it("should reject non-image files", async () => {
      // Create a temporary text file
      const textFilePath = path.join(process.cwd(), "test-file.txt");
      fs.writeFileSync(textFilePath, "This is a text file");

      try {
        const res = await request(app)
          .post(`/api/users/${testUserId}/avatar`)
          .set("Authorization", `Bearer ${userToken}`)
          .attach("avatar", textFilePath);

        expect(res.status).toBe(StatusCodes.BAD_REQUEST);
        expect(res.body.error.message).toContain("image");
      } finally {
        fs.unlinkSync(textFilePath);
      }
    });

    it("should accept PNG images", async () => {
      // Create a minimal PNG file
      const pngBuffer = Buffer.from([
        0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d,
        0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
        0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4, 0x89, 0x00, 0x00, 0x00,
        0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
        0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49,
        0x45, 0x4e, 0x44, 0xae, 0x42, 0x60, 0x82,
      ]);
      const pngPath = path.join(process.cwd(), "test-avatar.png");
      fs.writeFileSync(pngPath, pngBuffer);

      try {
        const res = await request(app)
          .post(`/api/users/${testUserId}/avatar`)
          .set("Authorization", `Bearer ${userToken}`)
          .attach("avatar", pngPath);

        expect(res.status).toBe(StatusCodes.OK);
        expect(res.body.data.avatarPath).toMatch(/\.png$/);
      } finally {
        fs.unlinkSync(pngPath);
      }
    });

    it("should reject files larger than 5MB", async () => {
      // Create a file larger than 5MB
      const largeFilePath = path.join(process.cwd(), "large-file.jpg");
      const largeBuffer = Buffer.alloc(5 * 1024 * 1024 + 1); // 5MB + 1 byte
      fs.writeFileSync(largeFilePath, largeBuffer);

      try {
        const res = await request(app)
          .post(`/api/users/${testUserId}/avatar`)
          .set("Authorization", `Bearer ${userToken}`)
          .attach("avatar", largeFilePath);

        expect(res.status).toBe(StatusCodes.BAD_REQUEST);
      } finally {
        if (fs.existsSync(largeFilePath)) {
          fs.unlinkSync(largeFilePath);
        }
      }
    });
  });

  describe("POST /api/users/:id/avatar - Invalid input", () => {
    it("should return 400 for invalid user ID", async () => {
      const res = await request(app)
        .post("/api/users/invalid-id/avatar")
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.BAD_REQUEST);
    });

    it("should return 404 for non-existent user when admin uploads", async () => {
      const res = await request(app)
        .post("/api/users/99999/avatar")
        .set("Authorization", `Bearer ${adminToken}`)
        .attach("avatar", testImagePath);

      expect(res.status).toBe(StatusCodes.NOT_FOUND);
    });

    it("should return 403 for non-existent user when non-admin tries to upload", async () => {
      const res = await request(app)
        .post("/api/users/99999/avatar")
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      // Authorization is checked before existence, so forbidden comes first
      expect(res.status).toBe(StatusCodes.FORBIDDEN);
    });
  });

  describe("POST /api/users/:id/avatar - Multiple formats", () => {
    it("should accept GIF images", async () => {
      // Create a minimal GIF file
      const gifBuffer = Buffer.from([
        0x47, 0x49, 0x46, 0x38, 0x39, 0x61, 0x01, 0x00, 0x01, 0x00, 0x80, 0x00,
        0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x21, 0xf9, 0x04, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00,
        0x00, 0x02, 0x02, 0x44, 0x01, 0x00, 0x3b,
      ]);
      const gifPath = path.join(process.cwd(), "test-avatar.gif");
      fs.writeFileSync(gifPath, gifBuffer);

      try {
        const res = await request(app)
          .post(`/api/users/${testUserId}/avatar`)
          .set("Authorization", `Bearer ${userToken}`)
          .attach("avatar", gifPath);

        expect(res.status).toBe(StatusCodes.OK);
        expect(res.body.data.avatarPath).toMatch(/\.gif$/);
      } finally {
        fs.unlinkSync(gifPath);
      }
    });

    it("should accept WebP images", async () => {
      // Create a minimal WebP file
      const webpBuffer = Buffer.from([
        0x52, 0x49, 0x46, 0x46, 0x1a, 0x00, 0x00, 0x00, 0x57, 0x45, 0x42, 0x50,
        0x56, 0x50, 0x38, 0x20, 0x0e, 0x00, 0x00, 0x00, 0x30, 0x01, 0x00, 0x9d,
        0x01, 0x2a, 0x01, 0x00, 0x01, 0x00, 0x02, 0x00, 0x34, 0x25, 0xa4, 0x00,
        0x03, 0x70, 0x00, 0xfe, 0xfb, 0x94, 0x00, 0x00,
      ]);
      const webpPath = path.join(process.cwd(), "test-avatar.webp");
      fs.writeFileSync(webpPath, webpBuffer);

      try {
        const res = await request(app)
          .post(`/api/users/${testUserId}/avatar`)
          .set("Authorization", `Bearer ${userToken}`)
          .attach("avatar", webpPath);

        expect(res.status).toBe(StatusCodes.OK);
        expect(res.body.data.avatarPath).toMatch(/\.webp$/);
      } finally {
        fs.unlinkSync(webpPath);
      }
    });
  });

  describe("POST /api/users/:id/avatar - Edge cases", () => {
    it("should handle special characters in original filename", async () => {
      // Create a file with special characters
      const specialPath = path.join(process.cwd(), "test avatar (1) [copy].jpg");
      const jpegBuffer = Buffer.from([
        0xff, 0xd8, 0xff, 0xe0, 0x00, 0x10, 0x4a, 0x46, 0x49, 0x46, 0x00, 0x01,
        0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xff, 0xd9,
      ]);
      fs.writeFileSync(specialPath, jpegBuffer);

      try {
        const res = await request(app)
          .post(`/api/users/${testUserId}/avatar`)
          .set("Authorization", `Bearer ${userToken}`)
          .attach("avatar", specialPath);

        expect(res.status).toBe(StatusCodes.OK);
        expect(res.body.data.avatarPath).toBeTruthy();
      } finally {
        fs.unlinkSync(specialPath);
      }
    });

    it("should handle uploading multiple avatars for same user", async () => {
      const res1 = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      expect(res1.status).toBe(StatusCodes.OK);
      const firstPath = res1.body.data.avatarPath;

      const res2 = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      expect(res2.status).toBe(StatusCodes.OK);
      const secondPath = res2.body.data.avatarPath;

      // Paths should be different (new upload)
      expect(firstPath).not.toEqual(secondPath);

      // Verify the latest path is stored
      const unit = Unit.createReadonly();
      try {
        const user = unit.prepare("SELECT AvatarPath FROM User WHERE UserId = ?")
          .get(testUserId) as { AvatarPath: string };
        expect(user.AvatarPath).toEqual(secondPath);
      } finally {
        unit.complete();
      }
    });

    it("should preserve avatar path when updating user profile", async () => {
      const uploadRes = await request(app)
        .post(`/api/users/${testUserId}/avatar`)
        .set("Authorization", `Bearer ${userToken}`)
        .attach("avatar", testImagePath);

      const avatarPath = uploadRes.body.data.avatarPath;

      // Update user profile
      await request(app)
        .put(`/api/users/${testUserId}`)
        .set("Authorization", `Bearer ${userToken}`)
        .send({ userName: "updated-name", email: "updated@test.com" });

      // Verify avatar path is still there
      const unit = Unit.createReadonly();
      try {
        const user = unit.prepare("SELECT AvatarPath FROM User WHERE UserId = ?")
          .get(testUserId) as { AvatarPath: string };
        expect(user.AvatarPath).toEqual(avatarPath);
      } finally {
        unit.complete();
      }
    });
  });
});
