import express from "express";
import { StatusCodes } from "http-status-codes";
import { SchoolService } from "./school_service.js";
import { isAuthenticated, isAdmin, type AuthRequest } from "../middleware/auth_handlers.js";

export const schoolRouter = express.Router();
const schoolService: SchoolService = SchoolService.Instance;

// This swagger comment was generated by gemini
/**
 * @swagger
 * components:
 *   securitySchemes:
 *     bearerAuth:
 *       type: http
 *       scheme: bearer
 *       bearerFormat: JWT
 *   schemas:
 *     DrivingSchool:
 *       type: object
 *       properties:
 *         DrivingSchoolId:
 *           type: integer
 *         Name:
 *           type: string
 *         Location:
 *           type: string
 *           nullable: true
 *         Owner:
 *           type: string
 *           nullable: true
 *         Email:
 *           type: string
 *           nullable: true
 *         Website:
 *           type: string
 *           nullable: true
 * */

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/schools:
 *   get:
 *     summary: Retrieve a list of driving schools
 *     tags: [Schools]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: A list of driving schools.
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 $ref: '#/components/schemas/DrivingSchool'
 */
schoolRouter.get("/", isAuthenticated, (req, res) => {
  try {
    const userId = (req as AuthRequest).payload?.user.UserId;
    const schools = schoolService.getAllSchools(userId);
    res.status(StatusCodes.OK).json(schools);
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/schools/count:
 *   get:
 *     summary: Retrieve the total number of driving schools
 *     tags: [Schools]
 *     security: []
 *     responses:
 *       200:
 *         description: The total number of driving schools.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 count:
 *                   type: integer
 */
schoolRouter.get("/count", (req, res) => {
  try {
    const count = schoolService.getSchoolCount();
    res.status(StatusCodes.OK).json({ count });
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/schools/{schoolId}:
 *   get:
 *     summary: Retrieve a single driving school
 *     tags: [Schools]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: schoolId
 *         required: true
 *         schema:
 *           type: integer
 *         description: The ID of the school to retrieve
 *     responses:
 *       200:
 *         description: A single driving school.
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/DrivingSchool'
 *       404:
 *         description: School not found
 *       400:
 *         description: Invalid schoolId
 */
schoolRouter.get("/:schoolId", isAuthenticated, (req, res) => {
  try {
    const id = parseInt(req.params.schoolId);
    const result = schoolService.getSchoolById(id);
    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json(result.data);
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});

schoolRouter.put("/:schoolId", isAuthenticated, (req, res) => {
  try {
    const id = parseInt(req.params.schoolId);
    const tokenUser = (req as AuthRequest).payload?.user as any;
    if (tokenUser?.DrivingSchoolId !== id && tokenUser?.Role !== "admin") {
      res.status(StatusCodes.FORBIDDEN).json({ error: { message: "Not authorized" } });
      return;
    }
    const { name, location, owner, email, website, phone, openingDays, openingTimeFrom, openingTimeTo } = req.body;
    if (!name) {
      res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Name is required" } });
      return;
    }
    const result = schoolService.updateSchool(id, name, location, owner, email, website, phone, openingDays, openingTimeFrom, openingTimeTo);
    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json({ data: { message: "School updated" } });
    }
  } catch (error) {
    res
      .status(StatusCodes.INTERNAL_SERVER_ERROR)
      .json({ error: { message: (error as Error).message } });
  }
});
