// These tests were generated by Gemini
import request from "supertest";
import { app } from "../app.js";
import { StatusCodes } from "http-status-codes";

describe("School API", () => {
  it("GET /api/schools should return 401 without authentication", async () => {
    const res = await request(app).get("/api/schools");
    expect(res.status).toBe(StatusCodes.UNAUTHORIZED);
  });

  it("GET /api/schools/:schoolId should return 401 without authentication", async () => {
    // We assume ID 1 exists because sample data is inserted on startup
    const res = await request(app).get("/api/schools/1");
    expect(res.status).toBe(StatusCodes.UNAUTHORIZED);
  });

  it("GET /api/schools/:schoolId should return 401 for invalid ID without authentication", async () => {
    const res = await request(app).get("/api/schools/invalid");
    expect(res.status).toBe(StatusCodes.UNAUTHORIZED);
  });

  it("GET /api/schools/count should return the total number of schools", async () => {
    const res = await request(app).get("/api/schools/count");
    expect(res.status).toBe(StatusCodes.OK);
    expect(res.body).toHaveProperty("count");
    expect(typeof res.body.count).toBe("number");
  });
});
