import BetterSqlite3 from "better-sqlite3";
import type { Database, Statement } from "better-sqlite3";
import { Unit } from "./unit.js";

// create table statements generated by ai based on the uml at the bottom of the file
export const buildTables = (connection: Database) => {
  try {
    connection.exec(
        `CREATE TABLE IF NOT EXISTS User (
        UserId INTEGER PRIMARY KEY AUTOINCREMENT,
        UserName TEXT NOT NULL,
        Email TEXT NOT NULL UNIQUE,
        PasswordHash TEXT NOT NULL,
        Role TEXT NOT NULL DEFAULT 'user'
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS DrivingSchool (
        DrivingSchoolId INTEGER PRIMARY KEY AUTOINCREMENT,
        Name TEXT NOT NULL,
        Location TEXT,
        Owner TEXT,
        Email TEXT,
        Website TEXT
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS DocType (
        DocTypeId INTEGER PRIMARY KEY AUTOINCREMENT,
        ExpirationDuration INTEGER -- duration in days
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS LicenseType (
        LicenseTypeId INTEGER PRIMARY KEY AUTOINCREMENT,
        Name TEXT NOT NULL
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS LicenseProgram (
        LicenseProgramId INTEGER PRIMARY KEY AUTOINCREMENT,
        DrivingSchoolId INTEGER NOT NULL,
        LicenseTypeId INTEGER NOT NULL,
        FOREIGN KEY (DrivingSchoolId) REFERENCES DrivingSchool(DrivingSchoolId) ON DELETE CASCADE,
        FOREIGN KEY (LicenseTypeId) REFERENCES LicenseType(LicenseTypeId) ON DELETE CASCADE
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS Enrollment (
        EnrollmentId INTEGER PRIMARY KEY AUTOINCREMENT,
        UserId INTEGER NOT NULL,
        LicenseProgramId INTEGER NOT NULL,
        StartTime TEXT,
        FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE,
        FOREIGN KEY (LicenseProgramId) REFERENCES LicenseProgram(LicenseProgramId) ON DELETE CASCADE
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS Appointment (
        AppointmentId INTEGER PRIMARY KEY AUTOINCREMENT,
        EnrollmentId INTEGER NOT NULL,
        DateTime TEXT NOT NULL,
        Location TEXT,
        FOREIGN KEY (EnrollmentId) REFERENCES Enrollment(EnrollmentId) ON DELETE CASCADE
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS Document (
        DocumentId INTEGER PRIMARY KEY AUTOINCREMENT,
        EnrollmentId INTEGER NOT NULL,
        DocTypeId INTEGER NOT NULL,
        StartTime TEXT,
        FilePath TEXT NOT NULL,
        FOREIGN KEY (EnrollmentId) REFERENCES Enrollment(EnrollmentId) ON DELETE CASCADE,
        FOREIGN KEY (DocTypeId) REFERENCES DocType(DocTypeId) ON DELETE CASCADE
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS Rating (
        RatingId INTEGER PRIMARY KEY AUTOINCREMENT,
        UserId INTEGER NOT NULL,
        DrivingSchoolId INTEGER NOT NULL,
        Stars INTEGER NOT NULL CHECK (Stars BETWEEN 1 AND 5),
        Content TEXT,
        Date TEXT,
        FOREIGN KEY (UserId) REFERENCES User(UserId) ON DELETE CASCADE,
        FOREIGN KEY (DrivingSchoolId) REFERENCES DrivingSchool(DrivingSchoolId) ON DELETE CASCADE
      );`,
      );

    connection.exec(
        `CREATE TABLE IF NOT EXISTS Comment (
        CommentId INTEGER PRIMARY KEY AUTOINCREMENT,
        RatingId INTEGER NOT NULL,
        ParentCommentId INTEGER,
        Content TEXT NOT NULL,
        FOREIGN KEY (RatingId) REFERENCES Rating(RatingId) ON DELETE CASCADE,
        FOREIGN KEY (ParentCommentId) REFERENCES Comment(CommentId) ON DELETE CASCADE
      );`,
      );
  } catch (err) {
    throw err;
  }
};

export default buildTables;

/*
This is the current database structure:

@startuml

entity User{
  UserId
  UserName
  Email
}

entity DrivingSchool{
  DrivingSchoolId
  Name
  Location
  Owner
  Email
  Website
}

entity Document{
  DocumentId
  StartTime
  FilePath
}

entity DocType{
  DocTypeId
  ExpirationDuration
}

entity Appointment{
  AppointmentId
  DateTime
  Location
}

entity LicenseType{
  LicenseTypeId
  Name
}

entity Enrollment{
  EnrollmentId
  StartTime
}

entity Rating{
    RatingId
    Stars
    Content
    Date
}

entity Comment{
  CommentId
  Content
}

entity LicenseProgram {
  LicenseProgramId
}


Rating "1" -- "0..*" Comment
Comment "0..1" -- "0..*" Comment : Parent

Enrollment "1" -- "*" Document
DocType "1" -- "*" Document
Appointment "*" -- "1" Enrollment
DrivingSchool "1" -- "*" LicenseProgram
User "1" -- "*" Enrollment
LicenseProgram "1" -- "*" Enrollment
LicenseType "1" -- "*" LicenseProgram
Rating "*" -- "1" User
Rating "*" -- "1" DrivingSchool

@enduml
*/
