// These tests were generated by Gemini
import request from "supertest";
import { app } from "../app.js";
import { Unit } from "../unit.js";
import { ProgramRepository } from "./program_repository.js";
import jwt from "jsonwebtoken";
import { SECRET_KEY } from "../middleware/auth_handlers.js";

describe("Program Enrollment Endpoints", () => {
  let adminId: number;
  let userId1: number;
  let userId2: number;
  
  let adminToken: string;
  let userToken1: string;

  beforeAll(() => {
    const unit = new Unit(false);
    try {
      // Ensure test school and license type exist
      unit.prepare(`INSERT INTO DrivingSchool (DrivingSchoolId, Name) VALUES (1, 'Test School') ON CONFLICT DO NOTHING`).run();
      unit.prepare(`INSERT INTO LicenseType (LicenseTypeId, Name) VALUES (1, 'B') ON CONFLICT DO NOTHING`).run();

      const r1 = unit.prepare(`INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES ('Admin', ?, 'pw', 'admin') RETURNING UserId`)
        .get(`admin-${Date.now()}@example.com`) as { UserId: number };
      adminId = r1.UserId;

      const r2 = unit.prepare(`INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES ('User 1', ?, 'pw', 'user') RETURNING UserId`)
        .get(`user1-${Date.now()}@example.com`) as { UserId: number };
      userId1 = r2.UserId;

      const r3 = unit.prepare(`INSERT INTO User (UserName, Email, PasswordHash, Role) VALUES ('User 2', ?, 'pw', 'user') RETURNING UserId`)
        .get(`user2-${Date.now()}@example.com`) as { UserId: number };
      userId2 = r3.UserId;

      unit.complete(true);
    } catch {
      unit.complete(false);
    }

    adminToken = jwt.sign(
      { user: { UserId: adminId, Role: "admin", Email: "admin@example.com" } },
      SECRET_KEY,
      { expiresIn: "1h" }
    );

    userToken1 = jwt.sign(
      { user: { UserId: userId1, Role: "user", Email: "user1@example.com" } },
      SECRET_KEY,
      { expiresIn: "1h" }
    );
  });

  afterAll(() => {
    const unit = new Unit(false);
    try {
      unit.prepare(`DELETE FROM User WHERE UserId IN (?, ?, ?)`).run(adminId, userId1, userId2);
      unit.complete(true);
    } catch {
      unit.complete(false);
    }
  });

  const doSeedProgram = (maxParticipants: number, currentParticipants: number = 0) => {
    const unit = new Unit(false);
    let id;
    try {
      id = ProgramRepository.create(unit, {
        DrivingSchoolId: 1,
        LicenseTypeId: 1,
        DateFrom: "2024-01-01",
        DateTo: "2024-12-31",
        Price: 1000,
        MaxParticipants: maxParticipants,
        CurrentParticipants: currentParticipants,
      });
      unit.complete(true);
    } catch {
      unit.complete(false);
    }
    return id;
  };

  it("POST /api/programs/:id/enroll should enroll user and update participants", async () => {
    const programId = doSeedProgram(10, 0);
    
    const res = await request(app)
      .post(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${userToken1}`)
      .send();

    if (res.status !== 201) console.error("RES BODY", res.body);
    expect(res.status).toBe(201);
    expect(res.body.data.message).toBe("Successfully enrolled");

    const unit = Unit.createReadonly();
    const program = ProgramRepository.findById(unit, programId!);
    unit.complete();
    expect(program?.CurrentParticipants).toBe(1);
  });

  it("POST /api/programs/:id/enroll should fail if program is full", async () => {
    const programId = doSeedProgram(2, 2);
    
    const res = await request(app)
      .post(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${userToken1}`)
      .send();

    expect(res.status).toBe(400);
    expect(res.body.error.message).toBe("Program is full");
  });

  it("DELETE /api/programs/:id/enroll should unenroll user and update participants", async () => {
    const programId = doSeedProgram(10, 1);
    const unit = new Unit(false);
    ProgramRepository.enrollUser(unit, userId1, programId!);
    unit.complete(true);

    const res = await request(app)
      .delete(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${userToken1}`)
      .send();

    expect(res.status).toBe(200);
    expect(res.body.data.message).toBe("Successfully unenrolled");

    const checkUnit = Unit.createReadonly();
    const program = ProgramRepository.findById(checkUnit, programId!);
    const enrollment = ProgramRepository.checkEnrollment(checkUnit, userId1, programId!);
    checkUnit.complete();
    expect(program?.CurrentParticipants).toBe(0);
    expect(enrollment).toBeUndefined();
  });

  it("DELETE /api/programs/:id/enroll should fail if user not enrolled", async () => {
    const programId = doSeedProgram(10, 0);
    
    const res = await request(app)
      .delete(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${userToken1}`)
      .send();

    expect(res.status).toBe(400);
    expect(res.body.error.message).toBe("User is not enrolled in this program");
  });

  it("POST /api/programs/:id/enroll allows admin to enroll another user", async () => {
    const programId = doSeedProgram(10, 0);
    
    const res = await request(app)
      .post(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ userId: userId2 });

    expect(res.status).toBe(201);
    
    const unit = Unit.createReadonly();
    const enrollment = ProgramRepository.checkEnrollment(unit, userId2, programId!);
    unit.complete();
    expect(enrollment).toBeDefined();
  });

  it("POST /api/programs/:id/enroll forbids user from enrolling another user", async () => {
    const programId = doSeedProgram(10, 0);
    
    const res = await request(app)
      .post(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${userToken1}`)
      .send({ userId: userId2 });

    expect(res.status).toBe(403);
  });

  it("DELETE /api/programs/:id/enroll allows admin to unenroll another user", async () => {
    const programId = doSeedProgram(10, 1);
    const unit = new Unit(false);
    ProgramRepository.enrollUser(unit, userId2, programId!);
    unit.complete(true);

    const res = await request(app)
      .delete(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${adminToken}`)
      .send({ userId: userId2 });

    expect(res.status).toBe(200);

    const checkUnit = Unit.createReadonly();
    const enrollment = ProgramRepository.checkEnrollment(checkUnit, userId2, programId!);
    checkUnit.complete();
    expect(enrollment).toBeUndefined();
  });

  it("DELETE /api/programs/:id/enroll forbids user from unenrolling another user", async () => {
    const programId = doSeedProgram(10, 1);
    const unit = new Unit(false);
    ProgramRepository.enrollUser(unit, userId2, programId!);
    unit.complete(true);

    const res = await request(app)
      .delete(`/api/programs/${programId}/enroll`)
      .set("Authorization", `Bearer ${userToken1}`)
      .send({ userId: userId2 });

    expect(res.status).toBe(403);
  });
});
