import express from "express";
import type { Response } from "express";
import { StatusCodes } from "http-status-codes";
import { ProgramService } from "./program_service.js";
import { type AuthRequest, isAuthenticated } from "../middleware/auth_handlers.js";

const router = express.Router();

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/programs:
 *   post:
 *     summary: Create a new license program
 *     tags: [Programs]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - DrivingSchoolId
 *               - LicenseTypeId
 *               - DateFrom
 *               - DateTo
 *               - Price
 *               - MaxParticipants
 *             properties:
 *               DrivingSchoolId:
 *                 type: integer
 *               LicenseTypeId:
 *                 type: integer
 *               DateFrom:
 *                 type: string
 *               DateTo:
 *                 type: string
 *               Weekdays:
 *                 type: string
 *               IsSchnellkurs:
 *                 type: integer
 *               Price:
 *                 type: number
 *               MaxParticipants:
 *                 type: integer
 *     responses:
 *       201:
 *         description: Program created successfully
 *       400:
 *         description: Invalid input
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden (Only schools or admins)
 */
router.post("/", isAuthenticated, async (req: AuthRequest, res: Response) => {
  const result = ProgramService.Instance.createProgram(req.body, req.payload!.user.Role);
  if (result.error) {
    res.status(result.status).json({ error: result.error });
  } else {
    res.status(result.status).json({ data: result.data });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/programs/school/{schoolId}:
 *   get:
 *     summary: Get all programs for a specific driving school
 *     tags: [Programs]
 *     parameters:
 *       - in: path
 *         name: schoolId
 *         required: true
 *         schema:
 *           type: integer
 *     responses:
 *       200:
 *         description: List of programs
 */
router.get("/school/:schoolId", async (req, res) => {
  const schoolId = parseInt(req.params.schoolId);
  if (isNaN(schoolId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid school ID" } });
    return;
  }
  const result = ProgramService.Instance.getProgramsBySchool(schoolId);
  res.status(result.status).json({ data: result.data });
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/programs:
 *   get:
 *     summary: Get all license programs
 *     tags: [Programs]
 *     responses:
 *       200:
 *         description: List of all programs
 */
router.get("/", async (req, res) => {
  const result = ProgramService.Instance.getAllPrograms();
  res.status(result.status).json({ data: result.data });
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/programs/{id}/enroll:
 *   post:
 *     summary: Enroll a user in a program
 *     tags: [Programs]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *     requestBody:
 *       required: false
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userId:
 *                 type: integer
 *                 description: ID of the user to enroll (only for admins)
 *     responses:
 *       201:
 *         description: Successfully enrolled
 *       400:
 *         description: Invalid input or program full
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Program not found
 */
router.post("/:id/enroll", isAuthenticated, async (req: AuthRequest, res: Response) => {
  const programId = parseInt(req.params.id);
  if (isNaN(programId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid program ID" } });
    return;
  }
  
  const requestUserId = req.payload!.user.UserId;
  const requestUserRole = req.payload!.user.Role;
  const targetUserId = req.body?.userId ? parseInt(req.body.userId) : requestUserId;

  if (isNaN(targetUserId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid target user ID" } });
    return;
  }

  const result = ProgramService.Instance.enrollUser(programId, targetUserId, requestUserId, requestUserRole);
  if (result.error) {
    res.status(result.status).json({ error: result.error });
  } else {
    res.status(result.status).json({ data: result.data });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/programs/{id}/enroll:
 *   delete:
 *     summary: Unenroll a user from a program
 *     tags: [Programs]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: integer
 *     requestBody:
 *       required: false
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userId:
 *                 type: integer
 *                 description: ID of the user to unenroll (only for admins)
 *     responses:
 *       200:
 *         description: Successfully unenrolled
 *       400:
 *         description: Invalid input or user not enrolled
 *       401:
 *         description: Unauthorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Program not found
 */
router.delete("/:id/enroll", isAuthenticated, async (req: AuthRequest, res: Response) => {
  const programId = parseInt(req.params.id);
  if (isNaN(programId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid program ID" } });
    return;
  }
  
  const requestUserId = req.payload!.user.UserId;
  const requestUserRole = req.payload!.user.Role;
  const targetUserId = req.body?.userId ? parseInt(req.body.userId) : requestUserId;

  if (isNaN(targetUserId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid target user ID" } });
    return;
  }

  const result = ProgramService.Instance.unenrollUser(programId, targetUserId, requestUserId, requestUserRole);
  if (result.error) {
    res.status(result.status).json({ error: result.error });
  } else {
    res.status(result.status).json({ data: result.data });
  }
});

router.put("/:id", isAuthenticated, async (req: AuthRequest, res: Response) => {
  const programId = parseInt(req.params.id);
  if (isNaN(programId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid program ID" } });
    return;
  }
  const result = ProgramService.Instance.updateProgram(programId, req.body, req.payload!.user.Role);
  if (result.error) {
    res.status(result.status).json({ error: result.error });
  } else {
    res.status(result.status).json({ data: result.data });
  }
});

router.delete("/:id", isAuthenticated, async (req: AuthRequest, res: Response) => {
  const programId = parseInt(req.params.id);
  if (isNaN(programId)) {
    res.status(StatusCodes.BAD_REQUEST).json({ error: { message: "Invalid program ID" } });
    return;
  }
  const result = ProgramService.Instance.deleteProgram(programId, req.payload!.user.Role);
  if (result.error) {
    res.status(result.status).json({ error: result.error });
  } else {
    res.status(result.status).json({ data: result.data });
  }
});

export { router as programRouter };
