import express from "express";
import { AuthService } from "./auth_service.js";

export const authRouter = express.Router();
const authService = AuthService.Instance;

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/auth/login:
 *   post:
 *     summary: Login a user
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *     responses:
 *       200:
 *         description: Login successful
 *       401:
 *         description: Unauthorized
 */
authRouter.post("/login", async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) {
    res.status(400).json({ error: { message: "Email and password are required" } });
    return;
  }

  try {
    const result = await authService.login(email, password);
    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json(result.data);
    }
  } catch (error: any) {
    res.status(500).json({ error: { message: error.message || "Internal Server Error" } });
  }
});

// This swagger comment was generated by gemini
/**
 * @swagger
 * /api/auth/register:
 *   post:
 *     summary: Register a new user
 *     tags: [Auth]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userName:
 *                 type: string
 *               email:
 *                 type: string
 *               password:
 *                 type: string
 *               role:
 *                 type: string
 *               isSchool:
 *                 type: boolean
 *     responses:
 *       201:
 *         description: User created
 *       400:
 *         description: Bad request
 *       409:
 *         description: Conflict
 */
authRouter.post("/register", async (req, res) => {
  const { userName, email, password, role, isSchool, location, owner, phone, website, latitude, longitude } = req.body;
  if (!userName || !email || !password) {
    res.status(400).json({ error: { message: "Username, email and password are required" } });
    return;
  }

  try {
    const schoolData = isSchool ? { location, owner, phone, website, latitude, longitude } : undefined;
    const result = await authService.register(userName, email, password, role, isSchool, schoolData, location, latitude, longitude);
    if (result.error) {
      res.status(result.status).json({ error: result.error });
    } else {
      res.status(result.status).json({ data: result.data });
    }
  } catch (error: any) {
    res.status(500).json({ error: { message: error.message || "Internal Server Error" } });
  }
});
